# Generated by Django 5.2.1 on 2025-07-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_task_category_task_repeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
