# Generated by Django 5.2.1 on 2025-08-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_task_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="attachment",
            field=models.URLField(blank=True, null=True),
        ),
    ]
