# Generated by Django 5.2.1 on 2025-08-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0004_alter_task_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="repeat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=10,
                null=True,
            ),
        ),
    ]
